### ISSUE TITLE
aspectRatio={cover} bottom, top, left and right style not being applied correctly. 

### ISSUE THREAD

**Issue by swalker326** [purple-technology/react-camera-pro#7]
https://github.com/purple-technology/react-camera-pro/blob/a655126579a5174e494fbc31d96e7456b4b4f682/src/components/Camera/styles.ts#L12-L25

should be:

```
export const Container = styled.div<{ aspectRatio: AspectRatio }>`
  width: 100%;
  ${({ aspectRatio }) =>
    aspectRatio === 'cover'
      ? `
    position: absolute;
    bottom: 0;
    top: 0;
    left: 0;
    right: 0;`
      : `
    position: relative;
    padding-bottom: ${100 / aspectRatio}%;`}
`;

```

the positioning is not being applied correctly and aspectRatio={cover} is not working correctly, which is the default.

**Comment by LyDawei** [comment]
@swalker326 can you do a PR with your changes? Doesn't seem like there is any attention on this.
